name: Build Windows MSVC and Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build for Windows MSVC
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Create Windows package
      run: |
        mkdir -p dist/windows-msvc
        cp target/x86_64-pc-windows-msvc/release/dani_seres_do_papel.exe dist/windows-msvc/
        cp -r assets dist/windows-msvc/

    - name: Upload Windows MSVC artifact
      uses: actions/upload-artifact@v4
      with:
        name: dani-seres-do-papel-windows-msvc
        path: dist/windows-msvc/
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Create Linux package
      run: |
        mkdir -p dist/linux
        cp target/x86_64-unknown-linux-gnu/release/dani_seres_do_papel dist/linux/
        cp -r assets dist/linux/

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: dani-seres-do-papel-linux
        path: dist/linux/
        retention-days: 30

  release:
    needs: [build-windows-msvc, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: List downloaded files
      run: |
        echo "=== Listing downloaded artifacts ==="
        find artifacts/ -type f -name "*" | head -20
        echo "=== Windows artifacts ==="
        ls -la artifacts/dani-seres-do-papel-windows-msvc/ || echo "Windows artifacts not found"
        echo "=== Linux artifacts ==="
        ls -la artifacts/dani-seres-do-papel-linux/ || echo "Linux artifacts not found"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/dani-seres-do-papel-windows-msvc/dani_seres_do_papel.exe
          artifacts/dani-seres-do-papel-linux/dani_seres_do_papel
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 