name: Build Windows MSVC and Linux

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build for Windows MSVC
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Create Windows package with embedded assets
      run: |
        mkdir -p dist/windows-msvc
        cp target/x86_64-pc-windows-msvc/release/dani_seres_do_papel.exe dist/windows-msvc/
        cp -r assets dist/windows-msvc/
        
        # Criar arquivo ZIP com tudo
        cd dist/windows-msvc
        7z a -tzip dani-seres-do-papel-windows-msvc.zip dani_seres_do_papel.exe assets/
        cd ../..

    - name: Upload Windows MSVC artifact
      uses: actions/upload-artifact@v4
      with:
        name: dani-seres-do-papel-windows-msvc
        path: |
          dist/windows-msvc/dani_seres_do_papel.exe
          dist/windows-msvc/assets/
          dist/windows-msvc/dani-seres-do-papel-windows-msvc.zip
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Create Linux package with embedded assets
      run: |
        mkdir -p dist/linux
        cp target/x86_64-unknown-linux-gnu/release/dani_seres_do_papel dist/linux/
        cp -r assets dist/linux/
        
        # Criar arquivo TAR.GZ com tudo
        cd dist/linux
        tar -czf dani-seres-do-papel-linux.tar.gz dani_seres_do_papel assets/
        cd ../..

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: dani-seres-do-papel-linux
        path: |
          dist/linux/dani_seres_do_papel
          dist/linux/assets/
          dist/linux/dani-seres-do-papel-linux.tar.gz
        retention-days: 30

  release:
    needs: [build-windows-msvc, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/windows-msvc/dani_seres_do_papel.exe
          dist/windows-msvc/assets/**
          dist/windows-msvc/dani-seres-do-papel-windows-msvc.zip
          dist/linux/dani_seres_do_papel
          dist/linux/assets/**
          dist/linux/dani-seres-do-papel-linux.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 