name: Build Windows MSVC

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build for Windows MSVC
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Create Windows package
      run: |
        mkdir -p dist/windows-msvc
        cp target/x86_64-pc-windows-msvc/release/dani_seres_do_papel.exe dist/windows-msvc/
        cp -r assets dist/windows-msvc/

    - name: Upload Windows MSVC artifact
      uses: actions/upload-artifact@v4
      with:
        name: dani-seres-do-papel-windows-msvc
        path: dist/windows-msvc/
        retention-days: 30

    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/windows-msvc/**
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 